# PyInstaller recipe for pz-agent.exe — the whole CLI in one file.
#
# Build it with:
#   pyinstaller --noconfirm --clean ^
#     --distpath packaging/windows/dist --workpath packaging/windows/build ^
#     packaging/windows/pz-agent.spec
#
# One file rather than a folder, because the installed product must be a thing a
# user can copy: the release ZIP holds bin\pz-agent.exe and the BAT files run it
# by path. Neither Python nor git is needed to run what this produces.
#
# The entry script is generated here rather than kept in the tree. The console
# script this executable stands in for is ``pz_agent_cli.__main__:main``, and
# that module cannot be handed to PyInstaller directly: it is a package member
# using relative imports, so executing it as a top-level script fails with
# "attempted relative import with no known parent package" *at runtime*, in the
# built binary, where the failure is furthest from anyone who can read it. A
# three-line generated launcher imports the package properly and keeps
# pyproject.toml's console_scripts the single definition of what runs.

from pathlib import Path

# SPECPATH is injected by PyInstaller when it executes this file.
SPEC_DIR = Path(SPECPATH).resolve()  # noqa: F821  (PyInstaller global)
REPO_ROOT = SPEC_DIR.parents[1]

#: The source trees, mirroring pyproject.toml's ``tool.hatch.build.targets.wheel``.
#: pz_agent_voice is included because a build that omitted it would differ from
#: the wheel, and the difference would only surface when voice is switched on.
PACKAGES = ("pz_agent_core", "pz_agent_cli", "pz_agent_voice")
SRC_DIRS = [str(REPO_ROOT / "packages" / name / "src") for name in PACKAGES]

ENTRY_DIR = SPEC_DIR / "build" / "entry"
ENTRY = ENTRY_DIR / "pz-agent-entry.py"
ENTRY_DIR.mkdir(parents=True, exist_ok=True)
ENTRY.write_text(
    '"""Generated by packaging/windows/pz-agent.spec. Rewritten on every build."""\n'
    "\n"
    "from pz_agent_cli.__main__ import cli\n"
    "\n"
    'if __name__ == "__main__":\n'
    "    cli()\n",
    encoding="utf-8",
)

#: Imported inside a function so the package works without them, which is
#: exactly why PyInstaller's static analysis cannot see them:
#:   jsonschema — validates every live-test evidence document before it is written
#:   yaml       — reads the game-smoke scenario files
#: A missing one here does not break the build; it breaks the command that needs
#: it, months later, on the machine that has no way to install it.
HIDDEN = ["jsonschema", "yaml"]

a = Analysis(  # noqa: F821  (PyInstaller global)
    [str(ENTRY)],
    pathex=SRC_DIRS,
    binaries=[],
    # No data files: the mod payload ships beside the executable in the release
    # ZIP (mod\), not inside it. install.bat passes --source, so the copy the
    # user installs is the copy they can see and check.
    datas=[],
    hiddenimports=HIDDEN,
    hookspath=[],
    runtime_hooks=[],
    # tkinter and the test runners are megabytes of nothing this program uses.
    excludes=["tkinter", "unittest", "pytest", "mypy", "ruff"],
    noarchive=False,
)

pyz = PYZ(a.pure)  # noqa: F821  (PyInstaller global)

exe = EXE(  # noqa: F821  (PyInstaller global)
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name="pz-agent",
    debug=False,
    bootloader_ignore_signals=False,
    # Neither stripping nor UPX: this binary is unsigned already, and a packed
    # unsigned executable is the shape SmartScreen and most antivirus engines
    # treat as hostile. Saving a few megabytes is not worth a user being told
    # the thing they just downloaded is malware.
    strip=False,
    upx=False,
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
