# PyInstaller recipe for pz-agent-mcp.exe — the stdio MCP server in one file.
#
# Build it with:
#   pyinstaller --noconfirm --clean ^
#     --distpath packaging/windows/dist --workpath packaging/windows/build ^
#     packaging/windows/pz-agent-mcp.spec
#
# A separate executable rather than a subcommand of pz-agent, because an MCP
# client launches this one and speaks JSON-RPC over its stdin and stdout.
# Anything else printed there is a protocol error, so the process that talks to
# a client is kept apart from the one that talks to a person.
#
# The entry script is generated for the same reason as in pz-agent.spec: the
# real entry point, ``pz_agent_mcp.__main__:main``, is a package member with
# relative imports and cannot be run as a top-level script.

from pathlib import Path

from PyInstaller.utils.hooks import collect_submodules

# SPECPATH is injected by PyInstaller when it executes this file.
SPEC_DIR = Path(SPECPATH).resolve()  # noqa: F821  (PyInstaller global)
REPO_ROOT = SPEC_DIR.parents[1]

PACKAGES = ("pz_agent_core", "pz_agent_mcp")
SRC_DIRS = [str(REPO_ROOT / "packages" / name / "src") for name in PACKAGES]

ENTRY_DIR = SPEC_DIR / "build" / "entry"
ENTRY = ENTRY_DIR / "pz-agent-mcp-entry.py"
ENTRY_DIR.mkdir(parents=True, exist_ok=True)
ENTRY.write_text(
    '"""Generated by packaging/windows/pz-agent-mcp.spec. Rewritten on every build."""\n'
    "\n"
    "from pz_agent_mcp.__main__ import cli\n"
    "\n"
    'if __name__ == "__main__":\n'
    "    cli()\n",
    encoding="utf-8",
)

#: The SDK is imported inside functions (it is an optional extra, and every
#: other module in the package must import without it), so nothing static points
#: at it. Collected whole: the server touches three of its submodules by name
#: and the SDK resolves more of its own at import time.
HIDDEN = ["mcp", *collect_submodules("mcp")]

a = Analysis(  # noqa: F821  (PyInstaller global)
    [str(ENTRY)],
    pathex=SRC_DIRS,
    binaries=[],
    datas=[],
    hiddenimports=HIDDEN,
    hookspath=[],
    runtime_hooks=[],
    excludes=["tkinter", "unittest", "pytest", "mypy", "ruff"],
    noarchive=False,
)

pyz = PYZ(a.pure)  # noqa: F821  (PyInstaller global)

exe = EXE(  # noqa: F821  (PyInstaller global)
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name="pz-agent-mcp",
    debug=False,
    bootloader_ignore_signals=False,
    # See pz-agent.spec: an unsigned packed binary reads as malware to
    # SmartScreen, and this one is launched by a client rather than by a person
    # who could dismiss the warning.
    strip=False,
    upx=False,
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
