"""pz-agent core: diagnostics.

Bounded logs, replayable traces and a support bundle a user can inspect before
attaching it to a public issue (docs/blueprint/14_PACKAGING_AND_OPERATIONS.md
§14.7).

The invariant the whole package exists to hold: **redaction happens on the way
in.** Every writer here takes a
:class:`~pz_agent_core.diagnostics.redaction.Redactor` and runs the record
through it before any byte reaches a file, because a post-processing pass only
cleans the copies somebody remembered to run it over — and the file on disk is
the one that gets attached to the issue.
"""

from __future__ import annotations

from .bundle import (
    MANIFEST_NAME,
    MAX_ENTRIES,
    MAX_ENTRY_BYTES,
    MAX_TOTAL_BYTES,
    MAX_VERIFY_ENTRY_BYTES,
    BundleBuilder,
    BundleEntry,
    BundleError,
    BundleVerification,
    SupportBundle,
    VerifiedEntry,
    verify_bundle,
)
from .log import (
    DEFAULT_KEEP,
    DEFAULT_LIMITS,
    DEFAULT_MAX_BYTES,
    DEFAULT_MAX_RECORD_BYTES,
    LEVEL_ORDER,
    MAX_EVENT_LEN,
    MAX_FIELDS,
    DiagnosticLog,
    DiagnosticsError,
    LogLevel,
    LogLimits,
    LogRecord,
    RotatingWriter,
    iso_from_ms,
    read_records,
)
from .redaction import (
    ELIDED,
    GENERIC_PATH_RULES,
    INSTALL_PLACEHOLDER,
    MAX_DEPTH,
    MAX_ITEMS,
    MAX_SCAN_CHARS,
    MAX_STRING_LEN,
    PATH_PLACEHOLDER,
    SECRET_KEY_RE,
    SECRET_PLACEHOLDER,
    SECRET_RULES,
    STEAM_ID_PLACEHOLDER,
    TRUNCATION_MARKER,
    USER_DIR_PLACEHOLDER,
    USER_HOME_PLACEHOLDER,
    USERNAME_PLACEHOLDER,
    RedactionError,
    RedactionRule,
    Redactor,
    build_redactor,
    null_redactor,
)
from .trace import (
    DEFAULT_TRACE_BYTES,
    DEFAULT_TRACE_KEEP,
    DEFAULT_TRACE_LIMITS,
    DEFAULT_TRACE_RECORD_BYTES,
    MAX_TRACE_ENTRIES,
    ReplayStep,
    TraceEntry,
    TraceError,
    TraceKind,
    TraceRead,
    TraceWriter,
    read_trace,
    replay_observations,
)

__all__ = [
    "DEFAULT_KEEP",
    "DEFAULT_LIMITS",
    "DEFAULT_MAX_BYTES",
    "DEFAULT_MAX_RECORD_BYTES",
    "DEFAULT_TRACE_BYTES",
    "DEFAULT_TRACE_KEEP",
    "DEFAULT_TRACE_LIMITS",
    "DEFAULT_TRACE_RECORD_BYTES",
    "ELIDED",
    "GENERIC_PATH_RULES",
    "INSTALL_PLACEHOLDER",
    "LEVEL_ORDER",
    "MANIFEST_NAME",
    "MAX_DEPTH",
    "MAX_ENTRIES",
    "MAX_ENTRY_BYTES",
    "MAX_EVENT_LEN",
    "MAX_FIELDS",
    "MAX_ITEMS",
    "MAX_SCAN_CHARS",
    "MAX_STRING_LEN",
    "MAX_TOTAL_BYTES",
    "MAX_TRACE_ENTRIES",
    "MAX_VERIFY_ENTRY_BYTES",
    "PATH_PLACEHOLDER",
    "SECRET_KEY_RE",
    "SECRET_PLACEHOLDER",
    "SECRET_RULES",
    "STEAM_ID_PLACEHOLDER",
    "TRUNCATION_MARKER",
    "USERNAME_PLACEHOLDER",
    "USER_DIR_PLACEHOLDER",
    "USER_HOME_PLACEHOLDER",
    "BundleBuilder",
    "BundleEntry",
    "BundleError",
    "BundleVerification",
    "DiagnosticLog",
    "DiagnosticsError",
    "LogLevel",
    "LogLimits",
    "LogRecord",
    "RedactionError",
    "RedactionRule",
    "Redactor",
    "ReplayStep",
    "RotatingWriter",
    "SupportBundle",
    "TraceEntry",
    "TraceError",
    "TraceKind",
    "TraceRead",
    "TraceWriter",
    "VerifiedEntry",
    "build_redactor",
    "iso_from_ms",
    "null_redactor",
    "read_records",
    "read_trace",
    "replay_observations",
    "verify_bundle",
]
