"""Wire protocol: enums, stable references, and message dataclasses.

Nothing in this package touches the filesystem, the game, or an LLM. It is the
shared vocabulary that the mod bridge, the action engine, the policy layer and
the MCP boundary all agree on.
"""

from __future__ import annotations

from .enums import (
    ALWAYS_ALLOWED_ACTIONS,
    MUTATING_MODES,
    ON_PERSON_CONTAINERS,
    READ_ONLY_ACTIONS,
    SELF_DIRECTED_MODES,
    TERMINAL_STATUSES,
    ActionName,
    ActionOwnership,
    ActionStatus,
    CapabilityState,
    ContainerKind,
    DangerLevel,
    Priority,
    RiskClass,
    SessionMode,
)
from .messages import (
    ActionResult,
    ActionState,
    Command,
    CommandPolicy,
    ContainerView,
    GameState,
    Hands,
    InventoryView,
    ItemView,
    JsonDict,
    NearbyObject,
    NearbyView,
    NearbyZombie,
    Observation,
    PlayerState,
    Position,
    ProtocolError,
    SafetyState,
    Wound,
)
from .reason_codes import PLAN_FATAL_CODES, RETRYABLE_CODES, ReasonCode
from .refs import (
    ContainerRef,
    ItemRef,
    RefError,
    RefKind,
    SquareRef,
    ZombieRef,
    belongs_to_session,
    ref_kind,
)

__all__ = [
    "ALWAYS_ALLOWED_ACTIONS",
    "MUTATING_MODES",
    "ON_PERSON_CONTAINERS",
    "PLAN_FATAL_CODES",
    "READ_ONLY_ACTIONS",
    "RETRYABLE_CODES",
    "SELF_DIRECTED_MODES",
    "TERMINAL_STATUSES",
    "ActionName",
    "ActionOwnership",
    "ActionResult",
    "ActionState",
    "ActionStatus",
    "CapabilityState",
    "Command",
    "CommandPolicy",
    "ContainerKind",
    "ContainerRef",
    "ContainerView",
    "DangerLevel",
    "GameState",
    "Hands",
    "InventoryView",
    "ItemRef",
    "ItemView",
    "JsonDict",
    "NearbyObject",
    "NearbyView",
    "NearbyZombie",
    "Observation",
    "PlayerState",
    "Position",
    "Priority",
    "ProtocolError",
    "ReasonCode",
    "RefError",
    "RefKind",
    "RiskClass",
    "SafetyState",
    "SessionMode",
    "SquareRef",
    "Wound",
    "ZombieRef",
    "belongs_to_session",
    "ref_kind",
]
