#!/usr/bin/env python3
"""Regenerate ``docs/control/STATUS.json`` from facts, never from memory.

STATUS.json was the file an independent monitor caught lying: it carried a HEAD
that was days old, a percentage of 50 that no calculation produced, a CI verdict
belonging to a different commit, and ``Open: none`` blockers next to a red build.
Every one of those was possible because the file was *written* rather than
*derived*.

So nothing here is typed by hand. The percentage comes from
``docs/control/MASTER_PLAN.yaml`` through the same function the report uses, the
HEAD comes from ``git rev-parse``, and the CI and RC verdicts have to be passed
in on the command line **with the commit they belong to** — a CI status with no
SHA cannot be recorded at all, which is what made "GREEN" stick around after the
commit it described had been superseded.

The rule that matters most is the last one: a workflow result for commit ``A``
is not evidence about commit ``B``. ``--linux-sha`` and ``--windows-sha`` are
required alongside their statuses, and if they do not equal the current HEAD the
status is written as ``STALE:<status>@<sha>`` rather than as the status itself.
A reader then cannot mistake it, and ``check_master_plan.py`` refuses a plan
whose STATUS claims a bare GREEN for a commit that is not HEAD.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path
from typing import Any, Final

REPO_ROOT: Final = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:  # pragma: no cover - import plumbing
    sys.path.insert(0, str(REPO_ROOT))

from scripts import check_master_plan, master_report  # noqa: E402

STATUS_PATH: Final = REPO_ROOT / "docs" / "control" / "STATUS.json"
PLAN_PATH: Final = REPO_ROOT / "docs" / "control" / "MASTER_PLAN.yaml"

#: The only words a CI field may carry when it describes the current HEAD.
CI_STATES: Final = ("GREEN", "RED", "PENDING", "NOT_RUN")

#: What an RC may be. CURRENT requires its source commit to equal HEAD; there is
#: no fourth state, because "recent" is the word that let a stale ZIP be treated
#: as a certification.
RC_STATES: Final = ("CURRENT", "STALE", "NOT_BUILT")


def head() -> str:
    return subprocess.run(
        ["git", "rev-parse", "HEAD"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
        timeout=60,
    ).stdout.strip()


def _ci_field(status: str, sha: str, current: str) -> dict[str, Any]:
    """A CI verdict, marked stale unless it belongs to the current HEAD."""
    if status not in CI_STATES:
        raise SystemExit(f"CI status must be one of {CI_STATES}, got {status!r}")
    belongs = sha == current
    return {
        "status": status if belongs else f"STALE:{status}",
        "commit": sha,
        "describes_current_head": belongs,
    }


def build(arguments: argparse.Namespace) -> dict[str, Any]:
    import yaml  # noqa: PLC0415

    document = yaml.safe_load(PLAN_PATH.read_text(encoding="utf-8"))
    tasks = check_master_plan.tasks_of(document)
    current = head()
    tally = master_report.counts(tasks)
    metrics = master_report.metric_values(document)

    rc_status = arguments.rc_status
    if rc_status not in RC_STATES:
        raise SystemExit(f"RC status must be one of {RC_STATES}, got {rc_status!r}")
    if rc_status == "CURRENT" and arguments.rc_sha != current:
        raise SystemExit(
            "an RC may only be CURRENT when it was built from the current HEAD; "
            f"HEAD is {current[:8]} and the RC came from {(arguments.rc_sha or 'nothing')[:8]}"
        )

    return {
        "$comment": (
            "Generated by scripts/reconcile_status.py. Do not edit by hand: every "
            "field here is derived, and a hand-written value is the defect this "
            "file exists to prevent."
        ),
        "repository": "https://github.com/natural0101/poject-zombigpt",
        "branch": subprocess.run(
            ["git", "branch", "--show-current"],
            cwd=REPO_ROOT,
            capture_output=True,
            text=True,
            check=True,
            timeout=60,
        ).stdout.strip(),
        "head_commit": current,
        "plan_of_record": "docs/control/MASTER_PLAN.yaml",
        "weighted_progress_percent": round(master_report.weighted(tasks), 2),
        "pass_weight": sum(int(t["weight"]) for t in tasks if t["status"] == "PASS"),
        "total_weight": sum(int(t["weight"]) for t in tasks),
        "total_tasks": len(tasks),
        "counts": tally,
        "metrics": {
            name: {"percent": round(percent, 1), "pass_weight": done, "total_weight": total}
            for name, (percent, done, total) in metrics.items()
        },
        "checks": {
            "pass": sum(1 for c in check_master_plan.checks_of(document) if c["status"] == "PASS"),
            "total": len(check_master_plan.checks_of(document)),
        },
        "linux_ci": _ci_field(arguments.linux, arguments.linux_sha, current),
        "windows_ci": _ci_field(arguments.windows, arguments.windows_sha, current),
        "release_candidate": {
            "status": rc_status,
            "source_commit": arguments.rc_sha,
            "workflow_run": arguments.rc_run,
            "archive_sha256": arguments.rc_sha256,
            "live_game": "NOT_RUN",
        },
        "live_scenarios": {"passed": 0, "failed": 0, "not_run": 20},
        "blockers_document": "docs/control/BLOCKERS.md",
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--linux", required=True, choices=CI_STATES)
    parser.add_argument("--linux-sha", required=True)
    parser.add_argument("--windows", required=True, choices=CI_STATES)
    parser.add_argument("--windows-sha", required=True)
    parser.add_argument("--rc-status", required=True, choices=RC_STATES)
    parser.add_argument("--rc-sha", default=None)
    parser.add_argument("--rc-run", default=None)
    parser.add_argument("--rc-sha256", default=None)
    arguments = parser.parse_args()

    document = build(arguments)
    STATUS_PATH.write_text(json.dumps(document, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(
        f"wrote {STATUS_PATH.relative_to(REPO_ROOT)}: "
        f"{document['weighted_progress_percent']}% at {document['head_commit'][:8]}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
