"""The typed goal channel: what a user, a model or a microphone may ask for.

Everything above the core — the MCP boundary, the CLI, the voice loop, a plan
provider — expresses intent through this package and through nothing else. That
is a narrow opening on purpose: :mod:`.model` holds a closed set of kinds whose
parameters are typed enums and range-checked numbers, and :mod:`.queue` holds a
bounded channel in which one goal runs at a time, every goal reaches a terminal
state, and every refusal says what failed and what to do without quoting a
single byte the caller supplied.

The channel does not decide *how* a goal is served. Selection stays in
:mod:`pz_agent_core.policy`, arbitration stays in :mod:`pz_agent_core.safety`,
and the lifecycle of a single command stays in :mod:`pz_agent_core.actions`;
:func:`~.model.to_planner_goal` is the one-line bridge to the deterministic
planner, and it is total, so a goal that cannot be served cannot be admitted.
"""

from __future__ import annotations

from .model import (
    DEFAULT_BUDGETS,
    GOAL_SPECS,
    MAX_DETAIL_CHARS,
    MAX_EVIDENCE_KEYS,
    MAX_GOAL_STEPS,
    MAX_GOAL_WALL_MS,
    MAX_IDEMPOTENCY_KEY_LEN,
    MAX_LOOT_CATEGORIES_CHARS,
    MAX_LOOT_RADIUS,
    MAX_PARSED_TOKEN_CHARS,
    MAX_PENDING_TTL_MS,
    MAX_RENDERED_VALUE_CHARS,
    MAX_SKILL_LEVEL,
    MAX_SLEEP_GOAL_HOURS,
    MAX_TARGET_FLOOR,
    MAX_TARGET_SQUARE,
    MIN_GOAL_WALL_MS,
    MIN_LOOT_RADIUS,
    MIN_TARGET_FLOOR,
    NUMERIC_RANGES,
    PARAM_NAMES,
    TERMINAL_GOAL_STATES,
    AreaScope,
    GoalAdmission,
    GoalBudget,
    GoalKind,
    GoalParams,
    GoalRecord,
    GoalRefusal,
    GoalRequest,
    GoalSpec,
    GoalState,
    GoalTransition,
    LootScope,
    NumericRange,
    TrainableSkill,
    key_digest,
    mint_goal_id,
    normalise_evidence_keys,
    parse_kind,
    parse_loot_categories,
    parse_scope,
    parse_skill,
    to_planner_goal,
)
from .persistence import (
    GOALS_FILE_NAME,
    GOALS_QUARANTINE_NAME,
    GOALS_SCHEMA_VERSION,
    MAX_GOAL_FILE_BYTES,
    MAX_PERSISTED_TERMINAL,
    MIN_SUPPORTED_GOALS_SCHEMA,
    GoalDocumentError,
    GoalStore,
    GoalStoreError,
    snapshot_from_document,
    snapshot_to_document,
)
from .queue import (
    DEFAULT_MAX_OPEN,
    DEFAULT_MAX_REMEMBERED,
    RESTART_LOST_DETAIL,
    GoalQueue,
    GoalSnapshot,
    UnknownGoalError,
)

__all__ = [
    "DEFAULT_BUDGETS",
    "DEFAULT_MAX_OPEN",
    "DEFAULT_MAX_REMEMBERED",
    "GOALS_FILE_NAME",
    "GOALS_QUARANTINE_NAME",
    "GOALS_SCHEMA_VERSION",
    "GOAL_SPECS",
    "MAX_DETAIL_CHARS",
    "MAX_EVIDENCE_KEYS",
    "MAX_GOAL_FILE_BYTES",
    "MAX_GOAL_STEPS",
    "MAX_GOAL_WALL_MS",
    "MAX_IDEMPOTENCY_KEY_LEN",
    "MAX_LOOT_CATEGORIES_CHARS",
    "MAX_LOOT_RADIUS",
    "MAX_PARSED_TOKEN_CHARS",
    "MAX_PENDING_TTL_MS",
    "MAX_PERSISTED_TERMINAL",
    "MAX_RENDERED_VALUE_CHARS",
    "MAX_SKILL_LEVEL",
    "MAX_SLEEP_GOAL_HOURS",
    "MAX_TARGET_FLOOR",
    "MAX_TARGET_SQUARE",
    "MIN_GOAL_WALL_MS",
    "MIN_LOOT_RADIUS",
    "MIN_SUPPORTED_GOALS_SCHEMA",
    "MIN_TARGET_FLOOR",
    "NUMERIC_RANGES",
    "PARAM_NAMES",
    "RESTART_LOST_DETAIL",
    "TERMINAL_GOAL_STATES",
    "AreaScope",
    "GoalAdmission",
    "GoalBudget",
    "GoalDocumentError",
    "GoalKind",
    "GoalParams",
    "GoalQueue",
    "GoalRecord",
    "GoalRefusal",
    "GoalRequest",
    "GoalSnapshot",
    "GoalSpec",
    "GoalState",
    "GoalStore",
    "GoalStoreError",
    "GoalTransition",
    "LootScope",
    "NumericRange",
    "TrainableSkill",
    "UnknownGoalError",
    "key_digest",
    "mint_goal_id",
    "normalise_evidence_keys",
    "parse_kind",
    "parse_loot_categories",
    "parse_scope",
    "parse_skill",
    "snapshot_from_document",
    "snapshot_to_document",
    "to_planner_goal",
]
